name: Run Selenium Script

on:
  push:
    branches:
      - main

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install selenium

      - name: Log Preinstalled Chrome and ChromeDriver Versions
        run: |
          echo "Using preinstalled ChromeDriver and Chrome"
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version

      - name: Add URLs Input File
        run: echo 'Ensure urls.json is included in the repository or upload it dynamically.'

      - name: Run Selenium script
        env:
          PATH: /usr/bin:$PATH
        run: python selenium_script.py

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: scraped-content
          path: scraped_content.json  # Output file from the script
