name: Run Selenium Script

on:
  push:
    branches:
      - main

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install selenium

      - name: Log Preinstalled Chrome and ChromeDriver Versions
        run: |
          echo "Using preinstalled ChromeDriver and Chrome"
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version

      - name: Validate Input File
        run: |
          if [ ! -f "chapters.json" ]; then
            echo "Input file 'chapters.json' not found. Please include it in the repository."
            exit 1
          fi

      - name: Run Selenium Script
        env:
          PATH: /usr/bin:$PATH
        run: python selenium_script.py

      - name: Verify Scraped Results Directory
        run: |
          if [ ! -d "scraped_results" ]; then
            echo "No 'scraped_results' directory found. Ensure the script ran successfully."
            exit 1
          fi

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: scraped-results
          path: scraped_results/*.json
